In [70]:
import pandas as pd
import numpy as np

In [71]:
df = pd.read_excel('Churn_Unclean_Project.xlsx')

In [72]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    str
 1   Customer_Name          533 non-null    str
 2   Gender                 536 non-null    str
 3   Age                    536 non-null    float64
 4   State                  531 non-null    str
 5   City                   539 non-null    str
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    str
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    str
 11  Payment_Method         526 non-null    str
 12  Internet_Service       535 non-null    str
 13  Tech_Support           530 non-null    str
 14  Senior_Citizen         534 non-null    str
 15  Dependents             539 non-null    str
 16  Churn                  538 non-null    str
 17  Last_Interaction_Date  539 non-null    str
dtypes: float64(4), str(14)
memory usage: 76.3 KB

In [74]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [75]:
df.shape

(542, 18)

In [76]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [77]:
df.duplicated().sum()

np.int64(7)

In [78]:
df.drop_duplicates(inplace=True)

In [79]:
df.duplicated().sum()

np.int64(0)

In [80]:
df.shape

(535, 18)

In [81]:
df.replace(['N/A','NULL','' ,' '],np.nan,inplace=True)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [82]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [83]:
df=df.apply(lambda x:x.str.strip() if x.dtype=="object" else x)

In [84]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium      180
Standard     168
Basic        165
Premium        3
basic          2
BASIC          2
Premium        1
Basic          1
Standard       1
  Basic        1
Name: count, dtype: int64

In [85]:
df["Customer_Name"]=df["Customer_Name"].str.title()
df["State"]=df["State"].str.title()
df["City"]=df["City"].str.title()
df["Subscription_Type"]=df["Subscription_Type"].str.title()
df["Contract_Type"]=df["Contract_Type"].str.title()

In [86]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium      180
Basic        169
Standard     168
Premium        3
Premium        1
Basic          1
Standard       1
  Basic        1
Name: count, dtype: int64

In [87]:
# df["Subscription_Type"] = df["Subscription_Type"].str.strip()
df["Subscription_Type"] = df["Subscription_Type"].str.title()

In [88]:
df["Subscription_Type"] = df["Subscription_Type"].str.strip().str.lower()
df["Subscription_Type"] = df["Subscription_Type"].replace({
    "premium": "Premium",
    "basic": "Basic",
    "standard": "Standard"
})

In [89]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium     184
Basic       171
Standard    169
Name: count, dtype: int64

In [90]:
df["Churn"].value_counts()

Churn
No     405
Yes    125
YES      1
yes      1
Name: count, dtype: int64

In [91]:
df["Churn"]=df["Churn"].str.title()

In [92]:
df["Gender"]=df["Gender"].str.title()

In [93]:
df["Gender"].value_counts()

Gender
Female    270
Male      258
 Male       2
Name: count, dtype: int64

In [94]:
cols=[
"Age",
"Tenure_Months",
"Monthly_Charges",
"Total_Charges"
]
for c in cols:
    df[c]=pd.to_numeric(df[c],errors="coerce")

In [95]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  529.000000     528.000000       523.000000     527.000000
mean    44.328922      36.518939      1329.967285   49739.683890
std     18.635396      20.659332       713.450173   41633.677902
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18818.270000
50%     44.000000      38.000000      1295.880000   40649.600000
75%     57.000000      54.000000      1879.020000   75126.770000
max    165.000000      72.000000      2492.510000  171429.830000

In [96]:
df=df[(df["Age"]>=18)&(df["Age"]<=100)]

In [97]:
df=df[df["Monthly_Charges"]>=0]
df=df[df["Total_Charges"]>=0]

In [98]:
df.shape

(492, 18)

In [99]:
df["Last_Interaction_Date"]=pd.to_datetime(
    df["Last_Interaction_Date"],
    errors="coerce"
)

In [100]:
# Fill Missing Values
df["Tech_Support"]=df["Tech_Support"].fillna("No")
df["Payment_Method"]=df["Payment_Method"].fillna("Unknown")
df["Monthly_Charges"]=df["Monthly_Charges"].fillna(df['Monthly_Charges'].mean())
df["Tenure_Months"]=df["Tenure_Months"].fillna(df['Tenure_Months'].mean())
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [101]:
df["Customer_Value"]=df["Monthly_Charges"]*df["Tenure_Months"]

In [102]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Customer_Value
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,2025-12-10,93627.08
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,Month-To-Month,Debit Card,5G,No,No,No,Yes,NaT,7215.39
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-02-04,1884.12
6,C1006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-To-Month,UPI,DSL,Yes,No,No,No,NaT,140618.10
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,NaT,125182.26

In [103]:
df["Monthly_Revenue"]=df["Monthly_Charges"]

In [104]:
df["Tenure_Group"]=pd.cut(
df["Tenure_Months"],
bins=[0,12,24,48,72],
labels=["0-12","13-24","25-48","49-72"]
)

In [105]:
df["Senior_Flag"]=np.where(df["Age"]>=60,"Senior","Adult")

In [106]:
df["Churn_Flag"]=df["Churn"].map({
"Yes":1,
"No":0
})

In [107]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    str
 1   Customer_Name          487 non-null    str
 2   Gender                 488 non-null    str
 3   Age                    492 non-null    float64
 4   State                  485 non-null    str
 5   City                   487 non-null    str
 6   Tenure_Months          492 non-null    float64
 7   Subscription_Type      486 non-null    str
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    str
 11  Payment_Method         492 non-null    str
 12  Internet_Service       486 non-null    str
 13  Tech_Support           492 non-null    str
 14  Senior_Citizen         486 non-null    str
 15  Dependents             491 non-null    str
 16  Churn                  490 non-null    str
 17  Last_Interaction_Date  178 non-null    datetime64[us]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    str
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[us](1), float64(7), str(14)
memory usage: 88.9 KB

Customer_ID                0
Customer_Name              5
Gender                     4
Age                        0
State                      7
City                       5
Tenure_Months              0
Subscription_Type          6
Monthly_Charges            0
Total_Charges              0
Contract_Type              2
Payment_Method             0
Internet_Service           6
Tech_Support               0
Senior_Citizen             6
Dependents                 1
Churn                      2
Last_Interaction_Date    314
Customer_Value             0
Monthly_Revenue            0
Tenure_Group               0
Senior_Flag                0
Churn_Flag                 2
dtype: int64

In [108]:
df["Last_Interaction_Date"]=df["Last_Interaction_Date"].fillna(df["Last_Interaction_Date"].median())

In [109]:
df['Tenure_Months'] = df['Tenure_Months'].astype(int)

In [110]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
Index: 492 entries, 0 to 540
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            492 non-null    str
 1   Customer_Name          487 non-null    str
 2   Gender                 488 non-null    str
 3   Age                    492 non-null    float64
 4   State                  485 non-null    str
 5   City                   487 non-null    str
 6   Tenure_Months          492 non-null    int64
 7   Subscription_Type      486 non-null    str
 8   Monthly_Charges        492 non-null    float64
 9   Total_Charges          492 non-null    float64
 10  Contract_Type          490 non-null    str
 11  Payment_Method         492 non-null    str
 12  Internet_Service       486 non-null    str
 13  Tech_Support           492 non-null    str
 14  Senior_Citizen         486 non-null    str
 15  Dependents             491 non-null    str
 16  Churn                  490 non-null    str
 17  Last_Interaction_Date  492 non-null    datetime64[us]
 18  Customer_Value         492 non-null    float64
 19  Monthly_Revenue        492 non-null    float64
 20  Tenure_Group           492 non-null    category
 21  Senior_Flag            492 non-null    str
 22  Churn_Flag             490 non-null    float64
dtypes: category(1), datetime64[us](1), float64(6), int64(1), str(14)
memory usage: 88.9 KB

Customer_ID              0
Customer_Name            5
Gender                   4
Age                      0
State                    7
City                     5
Tenure_Months            0
Subscription_Type        6
Monthly_Charges          0
Total_Charges            0
Contract_Type            2
Payment_Method           0
Internet_Service         6
Tech_Support             0
Senior_Citizen           6
Dependents               1
Churn                    2
Last_Interaction_Date    0
Customer_Value           0
Monthly_Revenue          0
Tenure_Group             0
Senior_Flag              0
Churn_Flag               2
dtype: int64

In [111]:
df.to_csv("Clean_Churn_Data.csv",index=False)

In [112]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Tajamul%401099@localhost:3306/CUSTOMER_CHURN_DB")

df.to_sql("customer_churn", con=engine, if_exists="replace", index=False)

492

In [113]:
df.to_sql(
    name="customer_churn",
    con=engine,
    if_exists="replace",
    index=False
)

492